CREATE TABLE note_item (
	id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL,
  content TEXT CHARACTER SET utf8mb4 NOT NULL,
  category VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL,
  `status` enum('Pending','Completed','Deleted') DEFAULT 'Pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);